const Db = [
    {
      id: "1",
      name: "analog circuit",
      author: "amar",
      image: "images/ac.jpg",
      subject: "ece",
      date: "2022-12-21",
    },
    {
        id: "2",
        name: "computer networks",
        author: "amar",
        image: "images/cn.jpg",
        subject: "ise",
        date: "2022-12-21",
      },
      {
        id: "3",
        name: "database management",
        author: "sona",
        image: "images/db.jpg",
        subject: "ise",
        date:  "2022-12-21",
      },
      {
        id: "4",
        name: "digital circuit",
        author: "sona",
        image: "images/dc.jpg",
        subject: "ece",
        date:  "2022-12-20",
      },
      {
        id: "5",
        name: "network theory",
        author: "amar",
        image: "images/nt.jpg",
        subject: "ece",
        date:  "2022-12-20",
      },
      {
        id: "6",
        name: "operating system",
        author: "amar",
        image: "images/os.jpg",
        subject: "ise",
        date:  "2022-12-20",
      },
      {
        id: "7",
        name: "system design",
        author: "amar",
        image: "images/sd.jpg",
        subject: "ece",
        date:  "2022-12-20",
      },
      {
        id: "8",
        name: "analog circuit",
        author: "amar",
        image: "images/ac.jpg",
        subject: "ece",
        date: "2022-12-21",
      },
      {
          id: "9",
          name: "computer networks",
          author: "amar",
          image: "images/cn.jpg",
          subject: "ise",
          date: "2022-12-21",
        },
        {
          id: "10",
          name: "database management",
          author: "sona",
          image: "images/db.jpg",
          subject: "ise",
          date:  "2022-12-21",
        },
        {
          id: "11",
          name: "digital circuit",
          author: "sona",
          image: "images/dc.jpg",
          subject: "ece",
          date:  "2022-12-20",
        },
        {
          id: "12",
          name: "network theory",
          author: "amar",
          image: "images/nt.jpg",
          subject: "ece",
          date:  "2022-12-20",
        },
        {
          id: "13",
          name: "operating system",
          author: "amar",
          image: "images/os.jpg",
          subject: "ise",
          date:  "2022-12-20",
        },
        {
          id: "14",
          name: "system design",
          author: "amar",
          image: "images/sd.jpg",
          subject: "ece",
          date:  "2022-12-20",
        },
        {
          id: "15",
          name: "analog circuit",
          author: "amar",
          image: "images/ac.jpg",
          subject: "ece",
          date: "2022-12-21",
        },
        {
            id: "16",
            name: "computer networks",
            author: "amar",
            image: "images/cn.jpg",
            subject: "ise",
            date: "2022-12-21",
          },
          {
            id: "17",
            name: "database management",
            author: "sona",
            image: "images/db.jpg",
            subject: "ise",
            date:  "2022-12-21",
          },
          {
            id: "18",
            name: "digital circuit",
            author: "sona",
            image: "images/dc.jpg",
            subject: "ece",
            date:  "2022-12-20",
          },
          {
            id: "19",
            name: "network theory",
            author: "amar",
            image: "images/nt.jpg",
            subject: "ece",
            date:  "2022-12-20",
          },
          {
            id: "20",
            name: "operating system",
            author: "amar",
            image: "images/os.jpg",
            subject: "ise",
            date:  "2022-12-20",
          },
          {
            id: "21",
            name: "system design",
            author: "amar",
            image: "images/sd.jpg",
            subject: "ece",
            date:  "2022-12-20",
          },
  ];
  
  export default Db;
  